version: 2

sources:
  - name: staging
    database: airbnb-prices-eu
    schema: airbnb_prices_eu_dataset

    tables:
      - name: france_listings   

      - name: germany_listings 

      - name: greece_listings 

      - name: italy_listings

      - name: portugal_listings

      - name: spain_listings

models:
  - name: stg_spain_listings
    description: ""
    columns:
      - name: country
        data_type: string
        description: ""

      - name: region
        data_type: string
        description: ""

      - name: city
        data_type: string
        description: ""

      - name: release_year
        data_type: int64
        description: ""

      - name: release_month
        data_type: int64
        description: ""

      - name: release_date
        data_type: date
        description: "Report release date"

      - name: listing_id
        data_type: int64
        description: ""
        tests:
          - not_null:
              severity: warn 

      - name: listing_name
        data_type: string
        description: ""

      - name: host_id
        data_type: int64
        description: ""

      - name: host_name
        data_type: string
        description: ""

      - name: neighbourhood_group
        data_type: string
        description: ""

      - name: neighbourhood
        data_type: string
        description: ""

      - name: latitude_longitude
        data_type: string
        description: ""

      - name: room_type
        data_type: string
        description: ""
        tests: 
          - accepted_values:
              values: "{{ var('room_type_values') }}"
              severity: warn
              quote: true

      - name: price
        data_type: float64
        description: ""
        tests:
          - not_null:
              severity: warn          

      - name: minimum_nights
        data_type: int64
        description: "minimum number of night stay for the listing (calendar rules may be different)"

      - name: number_of_reviews
        data_type: int64
        description: ""

      - name: last_review
        data_type: date
        description: "The date of the last/newest review"

      - name: reviews_per_month
        data_type: float64
        description: ""

      - name: calculated_host_listings_count
        data_type: int64
        description: "The number of listings the host has in the current scrape, in the city/region geography."

      - name: availability_365
        data_type: int64
        description: "The availability of the listing x days in the future as determined by the calendar. Note a listing may be available because it has been booked by a guest or blocked by the host."

      - name: number_of_reviews_ltm
        data_type: int64
        description: "The number of reviews the listing has (in the last 12 months)"

      - name: has_license
        data_type: boolean
        description: "If listing has license, then True"

  - name: stg_portugal_listings
    description: ""
    columns:
      - name: country
        data_type: string
        description: ""

      - name: region
        data_type: string
        description: ""

      - name: city
        data_type: string
        description: ""

      - name: release_year
        data_type: int64
        description: ""

      - name: release_month
        data_type: int64
        description: ""

      - name: release_date
        data_type: date
        description: ""

      - name: listing_id
        data_type: int64
        description: ""
        tests:
          - not_null:
              severity: warn 

      - name: listing_name
        data_type: string
        description: ""

      - name: host_id
        data_type: int64
        description: ""

      - name: host_name
        data_type: string
        description: ""

      - name: neighbourhood_group
        data_type: string
        description: ""

      - name: neighbourhood
        data_type: string
        description: ""

      - name: latitude_longitude
        data_type: string
        description: ""

      - name: room_type
        data_type: string
        description: ""
        tests: 
          - accepted_values:
              values: "{{ var('room_type_values') }}"
              severity: warn
              quote: true

      - name: price
        data_type: float64
        description: ""
        tests:
          - not_null:
              severity: warn          

      - name: minimum_nights
        data_type: int64
        description: "minimum number of night stay for the listing (calendar rules may be different)"

      - name: number_of_reviews
        data_type: int64
        description: ""

      - name: last_review
        data_type: date
        description: "The date of the last/newest review"

      - name: reviews_per_month
        data_type: float64
        description: ""

      - name: calculated_host_listings_count
        data_type: int64
        description: "The number of listings the host has in the current scrape, in the city/region geography."

      - name: availability_365
        data_type: int64
        description: "The availability of the listing x days in the future as determined by the calendar. Note a listing may be available because it has been booked by a guest or blocked by the host."

      - name: number_of_reviews_ltm
        data_type: int64
        description: "The number of reviews the listing has (in the last 12 months)"

      - name: has_license
        data_type: boolean
        description: "If listing has license, then True"

  - name: stg_italy_listings
    description: ""
    columns:
      - name: country
        data_type: string
        description: ""

      - name: region
        data_type: string
        description: ""

      - name: city
        data_type: string
        description: ""

      - name: release_year
        data_type: int64
        description: ""

      - name: release_month
        data_type: int64
        description: ""

      - name: release_date
        data_type: date
        description: ""

      - name: listing_id
        data_type: int64
        description: ""
        tests:
          - not_null:
              severity: warn 

      - name: listing_name
        data_type: string
        description: ""

      - name: host_id
        data_type: int64
        description: ""

      - name: host_name
        data_type: string
        description: ""

      - name: neighbourhood_group
        data_type: string
        description: ""

      - name: neighbourhood
        data_type: string
        description: ""

      - name: latitude_longitude
        data_type: string
        description: ""

      - name: room_type
        data_type: string
        description: ""
        tests: 
          - accepted_values:
              values: "{{ var('room_type_values') }}"
              severity: warn
              quote: true

      - name: price
        data_type: float64
        description: ""
        tests:
          - not_null:
              severity: warn          

      - name: minimum_nights
        data_type: int64
        description: "minimum number of night stay for the listing (calendar rules may be different)"

      - name: number_of_reviews
        data_type: int64
        description: ""

      - name: last_review
        data_type: date
        description: "The date of the last/newest review"

      - name: reviews_per_month
        data_type: float64
        description: ""

      - name: calculated_host_listings_count
        data_type: int64
        description: "The number of listings the host has in the current scrape, in the city/region geography."

      - name: availability_365
        data_type: int64
        description: "The availability of the listing x days in the future as determined by the calendar. Note a listing may be available because it has been booked by a guest or blocked by the host."

      - name: number_of_reviews_ltm
        data_type: int64
        description: "The number of reviews the listing has (in the last 12 months)"

      - name: has_license
        data_type: boolean
        description: "If listing has license, then True"

  - name: stg_greece_listings
    description: ""
    columns:
      - name: country
        data_type: string
        description: ""

      - name: region
        data_type: string
        description: ""

      - name: city
        data_type: string
        description: ""

      - name: release_year
        data_type: int64
        description: ""

      - name: release_month
        data_type: int64
        description: ""

      - name: release_date
        data_type: date
        description: ""

      - name: listing_id
        data_type: int64
        description: ""
        tests:
          - not_null:
              severity: warn 

      - name: listing_name
        data_type: string
        description: ""

      - name: host_id
        data_type: int64
        description: ""

      - name: host_name
        data_type: string
        description: ""

      - name: neighbourhood_group
        data_type: string
        description: ""

      - name: neighbourhood
        data_type: string
        description: ""

      - name: latitude_longitude
        data_type: string
        description: ""

      - name: room_type
        data_type: string
        description: ""
        tests: 
          - accepted_values:
              values: "{{ var('room_type_values') }}"
              severity: warn
              quote: true

      - name: price
        data_type: float64
        description: ""
        tests:
          - not_null:
              severity: warn          

      - name: minimum_nights
        data_type: int64
        description: "minimum number of night stay for the listing (calendar rules may be different)"

      - name: number_of_reviews
        data_type: int64
        description: ""

      - name: last_review
        data_type: date
        description: "The date of the last/newest review"

      - name: reviews_per_month
        data_type: float64
        description: ""

      - name: calculated_host_listings_count
        data_type: int64
        description: "The number of listings the host has in the current scrape, in the city/region geography."

      - name: availability_365
        data_type: int64
        description: "The availability of the listing x days in the future as determined by the calendar. Note a listing may be available because it has been booked by a guest or blocked by the host."

      - name: number_of_reviews_ltm
        data_type: int64
        description: "The number of reviews the listing has (in the last 12 months)"

      - name: has_license
        data_type: boolean
        description: "If listing has license, then True"

  - name: stg_france_listings
    description: ""
    columns:
      - name: country
        data_type: string
        description: ""

      - name: region
        data_type: string
        description: ""

      - name: city
        data_type: string
        description: ""

      - name: release_year
        data_type: int64
        description: ""

      - name: release_month
        data_type: int64
        description: ""

      - name: release_date
        data_type: date
        description: ""

      - name: listing_id
        data_type: int64
        description: ""
        tests:
          - not_null:
              severity: warn 

      - name: listing_name
        data_type: string
        description: ""

      - name: host_id
        data_type: int64
        description: ""

      - name: host_name
        data_type: string
        description: ""

      - name: neighbourhood_group
        data_type: string
        description: ""

      - name: neighbourhood
        data_type: string
        description: ""

      - name: latitude_longitude
        data_type: string
        description: ""

      - name: room_type
        data_type: string
        description: ""
        tests: 
          - accepted_values:
              values: "{{ var('room_type_values') }}"
              severity: warn
              quote: true

      - name: price
        data_type: float64
        description: ""
        tests:
          - not_null:
              severity: warn          

      - name: minimum_nights
        data_type: int64
        description: "minimum number of night stay for the listing (calendar rules may be different)"

      - name: number_of_reviews
        data_type: int64
        description: ""

      - name: last_review
        data_type: date
        description: "The date of the last/newest review"

      - name: reviews_per_month
        data_type: float64
        description: ""

      - name: calculated_host_listings_count
        data_type: int64
        description: "The number of listings the host has in the current scrape, in the city/region geography."

      - name: availability_365
        data_type: int64
        description: "The availability of the listing x days in the future as determined by the calendar. Note a listing may be available because it has been booked by a guest or blocked by the host."

      - name: number_of_reviews_ltm
        data_type: int64
        description: "The number of reviews the listing has (in the last 12 months)"

      - name: has_license
        data_type: boolean
        description: "If listing has license, then True"

  - name: stg_germany_listings
    description: ""
    columns:
      - name: country
        data_type: string
        description: ""

      - name: region
        data_type: string
        description: ""

      - name: city
        data_type: string
        description: ""

      - name: release_year
        data_type: int64
        description: ""

      - name: release_month
        data_type: int64
        description: ""

      - name: release_date
        data_type: date
        description: ""

      - name: listing_id
        data_type: int64
        description: ""
        tests:
          - not_null:
              severity: warn 

      - name: listing_name
        data_type: string
        description: ""

      - name: host_id
        data_type: int64
        description: ""

      - name: host_name
        data_type: string
        description: ""

      - name: neighbourhood_group
        data_type: string
        description: ""

      - name: neighbourhood
        data_type: string
        description: ""

      - name: latitude_longitude
        data_type: string
        description: ""

      - name: room_type
        data_type: string
        description: ""
        tests: 
          - accepted_values:
              values: "{{ var('room_type_values') }}"
              severity: warn
              quote: true

      - name: price
        data_type: float64
        description: ""
        tests:
          - not_null:
              severity: warn          

      - name: minimum_nights
        data_type: int64
        description: "minimum number of night stay for the listing (calendar rules may be different)"

      - name: number_of_reviews
        data_type: int64
        description: ""

      - name: last_review
        data_type: date
        description: "The date of the last/newest review"

      - name: reviews_per_month
        data_type: float64
        description: ""

      - name: calculated_host_listings_count
        data_type: int64
        description: "The number of listings the host has in the current scrape, in the city/region geography."

      - name: availability_365
        data_type: int64
        description: "The availability of the listing x days in the future as determined by the calendar. Note a listing may be available because it has been booked by a guest or blocked by the host."

      - name: number_of_reviews_ltm
        data_type: int64
        description: "The number of reviews the listing has (in the last 12 months)"

      - name: has_license
        data_type: boolean
        description: "If listing has license, then True"
